.\" Copyright (C)2008 Laurence Tratt http://tratt.net/laurie/
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to
.\" deal in the Software without restriction, including without limitation the
.\" rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
.\" sell copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
.\" IN THE SOFTWARE.
.Dd $Mdocdate: November 2 2008 $
.Dt EXTSMAIL 1
.Os
.Sh NAME
.Nm extsmail
.Nd robust sending of e-mail to external commands
.Sh SYNOPSIS
.Nm extsmail
.Op Ar options ...
.Sh DESCRIPTION
.Nm
masquerades as the standard UNIX
.Xr sendmail 1
when messages are sent; effectively, it notes the command line switches passed to
it, and puts those, and the message contents read from stdin, into a file in
a spool directory for later sending with
.Xr extsmaild 1 .
.Sh SEE ALSO
.Xr extsmail.conf 5 ,
.Xr extsmail.externals 5 ,
.Xr extsmaild 1
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Laurence Tratt Aq http://tratt.net/laurie/