.\" Copyright (C)2008 Laurence Tratt http://tratt.net/laurie/
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to
.\" deal in the Software without restriction, including without limitation the
.\" rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
.\" sell copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
.\" IN THE SOFTWARE.
.Dd $Mdocdate: November 2 2008 $
.Dt EXTSMAIL.CONF 5
.Os
.Sh NAME
.Nm extsmail.conf
.Nd configure robust sending of e-mail to external commands
.Sh DESCRIPTION
.Nm
is used to configure
.Xr extsmail 1
and
.Xr extsmaild 1 .
It consists of one or more 
.Em key = value
pairs. The following variables are defined:
.Bl -tag -width Ds
.It spool_dir
Sets the location of the spool directory used by
.Xr extsmail 1
and
.Xr extsmaild 1 .
This is the only variable which must be set in every configuration file.
.It notify_failure_interval
Specifies how often notifications of unsucessful deliveries should be made.
If unspecified, or set to 0, notifications will never be made. Times are
specified as a number followed by
.Em d
(days), 
.Em h
(hours),
.Em m
(minutes), or 
.Em s
(seconds).
.It notify_failure_cmd
The shell command to be executed when
.Em notify_failure_interval
seconds / minutes / hours / days have elapsed since the last fully
successful send cycle. If the string
.Em ${TIME}
exists in the command, it is replaced with a pretty printed string detailing
how much time has elapsed since the last fully successfuly send cycle.
The resulting string is then passed to
.Xr system 3 .
Note that no security checking is (or can be) done on the command, so this
option should be used with caution if a single configuration file serves
multiple users. Please check the warnings that come with
.Xr system 3 .
.It notify_success_cmd
The shell command to be executed when 1 or more messages have been successfully
sent. If the string
.Em ${SUCCESSES}
exists in the command, it is replaced with a string representing the number of
successfully sent messages. The same warnings that apply to
.Em notify_failure_cmd
also apply to this command.
.El
.Sh FILES
The
.Em extsmail
configuration file is searched for, in order, in the following locations:
.Pp
.Bl -tag -width Ds -compact
.It ~/.extsmail/conf
Per-user
.Em extsmail
configuration.
.Pp
.It /etc/extsmail/conf
System-wide
.Em extsmail
configuration.
.El
.Sh EXAMPLES
The simplest configuration file looks as follows:
.Bd -literal -offset indent
spool_dir = "~/somewhere"
.Ed
.Pp
A more complex configuration which uses a notification framework to inform the
user of mail sending and failure looks as follows:
.Bd -literal -offset indent
spool_dir = "~/somewhere"
notify_failure_interval = 30m
notify_failure_cmd = "notify-send \-a extsmaild \-c email
  \-i mail-send \-u critical 'extsmaild: ${TIME} since a fully
  successful send cycle'"
notify_success_cmd = "notify-send \-a extsmaild \-c email
  \-i mail-send \-u low 'extsmaild: ${SUCCESSES} messages
  successfully sent'"
.Ed
.Sh SEE ALSO
.Xr extsmail 1 ,
.Xr extsmail.externals 5 ,
.Xr extsmaild 1
.Sh AUTHORS
.An Laurence Tratt Aq http://tratt.net/laurie/
